"""P&C Streamlit Database Diagnostics — READ ONLY.

Place alongside pc-power-admin.py, or in pages/90_Database_Diagnostics.py.
Requires the repository's shared/pc_auth.py and the existing Supabase secrets.
All database operations are PostgREST SELECT only; no SQL/RPC, DDL or writes.
"""
from __future__ import annotations

import io
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import streamlit as st

# Works both as a standalone Streamlit entrypoint and as a page under pages/.
ROOT = Path(__file__).resolve().parent
if ROOT.name.lower() == "pages":
    ROOT = ROOT.parent
SHARED = ROOT / "shared"
if str(SHARED) not in sys.path:
    sys.path.insert(0, str(SHARED))
from pc_auth import require_super_admin, service_client

APP_VERSION = "phase13g-diagnostics-1.2"

PHASE13_TABLES_BY_PHASE = {'A': ['pc_research_projects',
       'pc_research_questions',
       'pc_research_claims',
       'pc_claim_evidence',
       'pc_research_hypotheses',
       'pc_research_opportunities',
       'pc_corridor_variants',
       'pc_corridor_exposures',
       'pc_monitoring_profiles',
       'pc_monitoring_rules',
       'pc_monitoring_observations',
       'pc_monitoring_alerts',
       'pc_weather_observations',
       'pc_event_updates',
       'pc_screening_cases',
       'pc_screening_matches',
       'pc_market_corridor_links'],
 'B': ['pc_company_offices',
       'pc_people',
       'pc_company_people_roles',
       'pc_company_portfolio_positions',
       'pc_company_asset_roles',
       'pc_company_milestones',
       'pc_company_corridor_roles',
       'pc_company_event_effects',
       'pc_canonical_identity_decisions'],
 'C': ['pc_vessel_identity_history',
       'pc_cruise_voyages',
       'pc_cruise_voyage_calls',
       'pc_passenger_incident_impacts',
       'pc_vessel_deployments',
       'pc_port_service_disruptions',
       'pc_inland_waterway_status'],
 'D': ['pc_rail_rolling_stock_units',
       'pc_rail_service_runs',
       'pc_rail_network_disruptions',
       'pc_road_network_links',
       'pc_trucking_fleet_assignments',
       'pc_road_border_observations',
       'pc_road_disruptions',
       'pc_air_service_movements',
       'pc_airspace_disruptions'],
 'E': ['pc_logistics_shipments',
       'pc_logistics_shipment_legs',
       'pc_logistics_service_agreements',
       'pc_corridor_mode_connections',
       'pc_freight_rate_assessments',
       'pc_supply_chain_dependencies',
       'pc_logistics_event_impacts'],
 'F': ['pc_defence_organisations',
       'pc_defence_programmes',
       'pc_defence_programme_participants',
       'pc_shipbuilding_production_tasks',
       'pc_defence_programme_milestones',
       'pc_shipyard_capacity_history',
       'pc_security_operations',
       'pc_security_operation_participants',
       'pc_security_attribution_claims']}

PHASE13_PK = {'pc_air_service_movements': 'air_service_movement_id',
 'pc_airspace_disruptions': 'airspace_disruption_id',
 'pc_canonical_identity_decisions': 'identity_decision_id',
 'pc_claim_evidence': 'claim_evidence_id',
 'pc_company_asset_roles': 'company_asset_role_id',
 'pc_company_corridor_roles': 'company_corridor_role_id',
 'pc_company_event_effects': 'company_event_effect_id',
 'pc_company_milestones': 'company_milestone_id',
 'pc_company_offices': 'company_office_id',
 'pc_company_people_roles': 'company_people_role_id',
 'pc_company_portfolio_positions': 'portfolio_position_id',
 'pc_corridor_exposures': 'corridor_exposure_id',
 'pc_corridor_mode_connections': 'corridor_mode_connection_id',
 'pc_corridor_variants': 'corridor_variant_id',
 'pc_cruise_voyage_calls': 'cruise_voyage_call_id',
 'pc_cruise_voyages': 'cruise_voyage_id',
 'pc_defence_organisations': 'entity_id',
 'pc_defence_programme_milestones': 'defence_milestone_id',
 'pc_defence_programme_participants': 'programme_participant_id',
 'pc_defence_programmes': 'defence_programme_id',
 'pc_event_updates': 'event_update_id',
 'pc_freight_rate_assessments': 'freight_rate_assessment_id',
 'pc_inland_waterway_status': 'waterway_status_id',
 'pc_logistics_event_impacts': 'logistics_event_impact_id',
 'pc_logistics_service_agreements': 'logistics_service_agreement_id',
 'pc_logistics_shipment_legs': 'shipment_leg_id',
 'pc_logistics_shipments': 'logistics_shipment_id',
 'pc_market_corridor_links': 'market_corridor_link_id',
 'pc_monitoring_alerts': 'monitoring_alert_id',
 'pc_monitoring_observations': 'monitoring_observation_id',
 'pc_monitoring_profiles': 'monitoring_profile_id',
 'pc_monitoring_rules': 'monitoring_rule_id',
 'pc_passenger_incident_impacts': 'passenger_incident_impact_id',
 'pc_people': 'person_id',
 'pc_port_service_disruptions': 'port_service_disruption_id',
 'pc_rail_network_disruptions': 'rail_disruption_id',
 'pc_rail_rolling_stock_units': 'rolling_stock_unit_id',
 'pc_rail_service_runs': 'rail_service_run_id',
 'pc_research_claims': 'research_claim_id',
 'pc_research_hypotheses': 'research_hypothesis_id',
 'pc_research_opportunities': 'research_opportunity_id',
 'pc_research_projects': 'research_project_id',
 'pc_research_questions': 'research_question_id',
 'pc_road_border_observations': 'road_border_observation_id',
 'pc_road_disruptions': 'road_disruption_id',
 'pc_road_network_links': 'road_network_link_id',
 'pc_screening_cases': 'screening_case_id',
 'pc_screening_matches': 'screening_match_id',
 'pc_security_attribution_claims': 'attribution_claim_id',
 'pc_security_operation_participants': 'security_operation_participant_id',
 'pc_security_operations': 'security_operation_id',
 'pc_shipbuilding_production_tasks': 'production_task_id',
 'pc_shipyard_capacity_history': 'shipyard_capacity_history_id',
 'pc_supply_chain_dependencies': 'supply_chain_dependency_id',
 'pc_trucking_fleet_assignments': 'trucking_fleet_assignment_id',
 'pc_vessel_deployments': 'vessel_deployment_id',
 'pc_vessel_identity_history': 'vessel_identity_history_id',
 'pc_weather_observations': 'weather_observation_id'}

PHASE13_COLUMNS = {'pc_air_service_movements': ['air_service_movement_id',
                              'transport_service_id',
                              'mobile_asset_id',
                              'operator_entity_id',
                              'departure_airport_asset_id',
                              'arrival_airport_asset_id',
                              'flight_number',
                              'scheduled_departure_at',
                              'actual_departure_at',
                              'scheduled_arrival_at',
                              'actual_arrival_at',
                              'movement_status',
                              'cargo_tonnes',
                              'passenger_count',
                              'related_event_id',
                              'source_id',
                              'research_claim_id',
                              'verification_status',
                              'metadata',
                              'created_at',
                              'updated_at'],
 'pc_airspace_disruptions': ['airspace_disruption_id',
                             'event_id',
                             'issuing_authority_entity_id',
                             'affected_airport_asset_id',
                             'fir_code',
                             'notam_reference',
                             'restriction_type',
                             'restriction_start_at',
                             'restriction_end_at',
                             'status',
                             'geographical_scope',
                             'source_id',
                             'research_claim_id',
                             'verification_status',
                             'metadata',
                             'created_at',
                             'updated_at'],
 'pc_canonical_identity_decisions': ['identity_decision_id',
                                     'source_entity_id',
                                     'canonical_entity_id',
                                     'match_status',
                                     'approval_status',
                                     'decision_reason',
                                     'reviewed_by_label',
                                     'reviewed_at',
                                     'source_id',
                                     'research_claim_id',
                                     'metadata',
                                     'created_at',
                                     'updated_at'],
 'pc_claim_evidence': ['claim_evidence_id',
                       'research_claim_id',
                       'evidence_role',
                       'source_id',
                       'source_record_uuid',
                       'document_id',
                       'source_url',
                       'source_locator',
                       'excerpt',
                       'observed_at',
                       'captured_at',
                       'metadata'],
 'pc_company_asset_roles': ['company_asset_role_id',
                            'entity_id',
                            'asset_id',
                            'mobile_asset_id',
                            'asset_role',
                            'role_status',
                            'valid_from',
                            'valid_to',
                            'as_of',
                            'source_id',
                            'research_claim_id',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_company_corridor_roles': ['company_corridor_role_id',
                               'entity_id',
                               'corridor_key',
                               'transport_service_id',
                               'corridor_role',
                               'role_status',
                               'valid_from',
                               'valid_to',
                               'as_of',
                               'source_id',
                               'research_claim_id',
                               'metadata',
                               'created_at',
                               'updated_at'],
 'pc_company_event_effects': ['company_event_effect_id',
                              'entity_id',
                              'event_id',
                              'corridor_key',
                              'effect_type',
                              'causal_status',
                              'observed_effect',
                              'start_at',
                              'end_at',
                              'source_id',
                              'research_claim_id',
                              'verification_status',
                              'metadata',
                              'created_at',
                              'updated_at'],
 'pc_company_milestones': ['company_milestone_id',
                           'entity_id',
                           'milestone_type',
                           'title',
                           'summary',
                           'milestone_date',
                           'date_precision',
                           'reported_at',
                           'event_id',
                           'transaction_id',
                           'related_entity_id',
                           'related_asset_id',
                           'milestone_status',
                           'source_id',
                           'research_claim_id',
                           'metadata',
                           'created_at',
                           'updated_at'],
 'pc_company_offices': ['company_office_id',
                        'entity_id',
                        'office_name',
                        'office_type',
                        'address_lines',
                        'city',
                        'region',
                        'country',
                        'postal_code',
                        'latitude',
                        'longitude',
                        'phone_public',
                        'email_public',
                        'website_url',
                        'site_asset_id',
                        'related_agent_entity_id',
                        'office_status',
                        'valid_from',
                        'valid_to',
                        'as_of',
                        'source_id',
                        'source_url',
                        'metadata',
                        'created_at',
                        'updated_at'],
 'pc_company_people_roles': ['company_people_role_id',
                             'entity_id',
                             'person_id',
                             'office_id',
                             'position_title',
                             'role_family',
                             'appointment_type',
                             'appointment_status',
                             'valid_from',
                             'valid_to',
                             'as_of',
                             'source_id',
                             'source_url',
                             'document_id',
                             'metadata',
                             'created_at',
                             'updated_at'],
 'pc_company_portfolio_positions': ['portfolio_position_id',
                                    'holder_entity_id',
                                    'investee_entity_id',
                                    'investee_asset_id',
                                    'investment_vehicle_entity_id',
                                    'position_type',
                                    'ownership_percent',
                                    'percentage_qualifier',
                                    'position_status',
                                    'valid_from',
                                    'valid_to',
                                    'as_of',
                                    'linked_transaction_id',
                                    'source_id',
                                    'research_claim_id',
                                    'metadata',
                                    'created_at',
                                    'updated_at'],
 'pc_corridor_exposures': ['corridor_exposure_id',
                           'corridor_key',
                           'corridor_variant_id',
                           'affected_segment_key',
                           'event_id',
                           'subject_type',
                           'subject_id',
                           'exposure_type',
                           'impact_status',
                           'impact_description',
                           'delay_hours',
                           'capacity_reduction_pct',
                           'observation_at',
                           'source_id',
                           'research_claim_id',
                           'metadata',
                           'created_at'],
 'pc_corridor_mode_connections': ['corridor_mode_connection_id',
                                  'corridor_key',
                                  'from_asset_id',
                                  'to_asset_id',
                                  'mode',
                                  'rail_link_id',
                                  'road_corridor_id',
                                  'transport_service_id',
                                  'transfer_capacity',
                                  'transfer_unit',
                                  'transfer_time_hours',
                                  'status',
                                  'valid_from',
                                  'valid_to',
                                  'source_id',
                                  'research_claim_id',
                                  'verification_status',
                                  'metadata',
                                  'created_at',
                                  'updated_at'],
 'pc_corridor_variants': ['corridor_variant_id',
                          'corridor_key',
                          'variant_name',
                          'variant_type',
                          'modes',
                          'route_segments',
                          'availability_status',
                          'capacity_value',
                          'capacity_unit',
                          'transit_time_hours',
                          'cost_basis',
                          'effective_from',
                          'effective_to',
                          'source_id',
                          'metadata',
                          'created_at',
                          'updated_at'],
 'pc_cruise_voyage_calls': ['cruise_voyage_call_id',
                            'cruise_voyage_id',
                            'port_asset_id',
                            'sequence_no',
                            'scheduled_arrival_at',
                            'actual_arrival_at',
                            'scheduled_departure_at',
                            'actual_departure_at',
                            'call_status',
                            'reported_delay_minutes',
                            'related_event_id',
                            'original_port_asset_id',
                            'source_id',
                            'research_claim_id',
                            'verification_status',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_cruise_voyages': ['cruise_voyage_id',
                       'cruise_itinerary_id',
                       'mobile_asset_id',
                       'cruise_line_entity_id',
                       'voyage_number',
                       'voyage_name',
                       'departure_at',
                       'expected_return_at',
                       'actual_return_at',
                       'homeport_asset_id',
                       'operational_status',
                       'passengers_reported',
                       'source_id',
                       'research_claim_id',
                       'verification_status',
                       'metadata',
                       'created_at',
                       'updated_at'],
 'pc_defence_organisations': ['entity_id',
                              'organisation_type',
                              'parent_entity_id',
                              'jurisdiction',
                              'public_mandate',
                              'establishment_date',
                              'organisation_status',
                              'source_id',
                              'research_claim_id',
                              'verification_status',
                              'metadata',
                              'created_at',
                              'updated_at'],
 'pc_defence_programme_milestones': ['defence_milestone_id',
                                     'defence_programme_id',
                                     'shipbuilding_order_unit_id',
                                     'event_id',
                                     'milestone_type',
                                     'planned_date',
                                     'actual_date',
                                     'milestone_status',
                                     'date_precision',
                                     'public_description',
                                     'source_id',
                                     'research_claim_id',
                                     'verification_status',
                                     'metadata',
                                     'created_at',
                                     'updated_at'],
 'pc_defence_programme_participants': ['programme_participant_id',
                                       'defence_programme_id',
                                       'entity_id',
                                       'shipyard_asset_id',
                                       'participant_role',
                                       'valid_from',
                                       'valid_to',
                                       'participation_status',
                                       'source_id',
                                       'research_claim_id',
                                       'verification_status',
                                       'metadata',
                                       'created_at',
                                       'updated_at'],
 'pc_defence_programmes': ['defence_programme_id',
                           'programme_name',
                           'customer_entity_id',
                           'lead_contractor_entity_id',
                           'shipbuilding_order_id',
                           'contract_id',
                           'programme_type',
                           'programme_status',
                           'announced_date',
                           'firm_quantity',
                           'option_quantity',
                           'announced_value',
                           'currency',
                           'expected_completion_date',
                           'source_id',
                           'research_claim_id',
                           'verification_status',
                           'metadata',
                           'created_at',
                           'updated_at'],
 'pc_event_updates': ['event_update_id',
                      'event_id',
                      'update_type',
                      'occurred_at',
                      'reported_at',
                      'published_at',
                      'source_id',
                      'source_record_uuid',
                      'document_id',
                      'summary',
                      'new_claims',
                      'review_status',
                      'metadata',
                      'created_at'],
 'pc_freight_rate_assessments': ['freight_rate_assessment_id',
                                 'market_observation_id',
                                 'corridor_key',
                                 'transport_service_id',
                                 'mode',
                                 'origin_asset_id',
                                 'destination_asset_id',
                                 'rate_category',
                                 'vessel_class',
                                 'observed_date',
                                 'rate_value',
                                 'rate_currency',
                                 'rate_unit',
                                 'assessment_kind',
                                 'publication_at',
                                 'licence_scope',
                                 'source_id',
                                 'research_claim_id',
                                 'verification_status',
                                 'metadata',
                                 'created_at',
                                 'updated_at'],
 'pc_inland_waterway_status': ['waterway_status_id',
                               'corridor_key',
                               'waterway_asset_id',
                               'observed_at',
                               'level_m',
                               'minimum_depth_m',
                               'maximum_draft_m',
                               'lock_status',
                               'ice_condition',
                               'restriction_status',
                               'restriction_start_at',
                               'restriction_end_at',
                               'related_event_id',
                               'source_id',
                               'research_claim_id',
                               'verification_status',
                               'metadata',
                               'created_at',
                               'updated_at'],
 'pc_logistics_event_impacts': ['logistics_event_impact_id',
                                'event_id',
                                'logistics_shipment_id',
                                'shipment_leg_id',
                                'transport_service_id',
                                'corridor_key',
                                'impact_type',
                                'status',
                                'measured_delay_hours',
                                'estimated_additional_cost',
                                'cost_currency',
                                'measured_at',
                                'causal_status',
                                'source_id',
                                'research_claim_id',
                                'verification_status',
                                'metadata',
                                'created_at',
                                'updated_at'],
 'pc_logistics_service_agreements': ['logistics_service_agreement_id',
                                     'contract_id',
                                     'customer_entity_id',
                                     'provider_entity_id',
                                     'agent_entity_id',
                                     'corridor_key',
                                     'transport_service_id',
                                     'service_type',
                                     'commodity',
                                     'minimum_volume',
                                     'volume_unit',
                                     'announced_at',
                                     'valid_from',
                                     'valid_to',
                                     'agreement_status',
                                     'source_id',
                                     'research_claim_id',
                                     'verification_status',
                                     'metadata',
                                     'created_at',
                                     'updated_at'],
 'pc_logistics_shipment_legs': ['shipment_leg_id',
                                'logistics_shipment_id',
                                'leg_no',
                                'mode',
                                'transport_service_id',
                                'operator_entity_id',
                                'mobile_asset_id',
                                'from_asset_id',
                                'to_asset_id',
                                'planned_start_at',
                                'actual_start_at',
                                'planned_end_at',
                                'actual_end_at',
                                'cost_amount',
                                'cost_currency',
                                'leg_status',
                                'source_id',
                                'research_claim_id',
                                'verification_status',
                                'metadata',
                                'created_at',
                                'updated_at'],
 'pc_logistics_shipments': ['logistics_shipment_id',
                            'shipment_reference',
                            'shipment_type',
                            'commodity_code',
                            'cargo_description',
                            'quantity',
                            'quantity_unit',
                            'origin_asset_id',
                            'destination_asset_id',
                            'shipper_entity_id',
                            'consignee_entity_id',
                            'corridor_key',
                            'departure_at',
                            'expected_arrival_at',
                            'actual_arrival_at',
                            'shipment_status',
                            'confidentiality_class',
                            'source_id',
                            'research_claim_id',
                            'verification_status',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_market_corridor_links': ['market_corridor_link_id',
                              'market_observation_id',
                              'corridor_key',
                              'corridor_variant_id',
                              'relevance_type',
                              'source_id',
                              'research_claim_id',
                              'metadata'],
 'pc_monitoring_alerts': ['monitoring_alert_id',
                          'monitoring_profile_id',
                          'monitoring_rule_id',
                          'monitoring_observation_id',
                          'event_id',
                          'headline',
                          'alert_status',
                          'severity',
                          'audience_codes',
                          'assessment',
                          'triggered_at',
                          'reviewed_at',
                          'sent_at',
                          'metadata',
                          'created_at',
                          'updated_at'],
 'pc_monitoring_observations': ['monitoring_observation_id',
                                'monitoring_profile_id',
                                'monitoring_rule_id',
                                'observed_at',
                                'reported_at',
                                'observation_type',
                                'event_id',
                                'corridor_key',
                                'target_type',
                                'target_id',
                                'source_id',
                                'source_record_uuid',
                                'research_claim_id',
                                'observation_data',
                                'confidence',
                                'review_status',
                                'created_at'],
 'pc_monitoring_profiles': ['monitoring_profile_id',
                            'profile_name',
                            'profile_domain',
                            'audience_codes',
                            'scope',
                            'active',
                            'owner_label',
                            'research_project_id',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_monitoring_rules': ['monitoring_rule_id',
                         'monitoring_profile_id',
                         'rule_name',
                         'rule_type',
                         'target_type',
                         'target_id',
                         'criteria',
                         'threshold',
                         'evaluation_interval_minutes',
                         'severity',
                         'active',
                         'valid_from',
                         'valid_to',
                         'metadata',
                         'created_at',
                         'updated_at'],
 'pc_passenger_incident_impacts': ['passenger_incident_impact_id',
                                   'event_id',
                                   'mobile_asset_id',
                                   'cruise_voyage_id',
                                   'ferry_route_id',
                                   'impact_type',
                                   'affected_passengers',
                                   'affected_crew',
                                   'delay_minutes',
                                   'reported_at',
                                   'operational_effect',
                                   'source_id',
                                   'research_claim_id',
                                   'verification_status',
                                   'metadata',
                                   'created_at',
                                   'updated_at'],
 'pc_people': ['person_id',
               'display_name',
               'normalized_name',
               'public_bio',
               'source_id',
               'source_url',
               'identity_status',
               'metadata',
               'created_at',
               'updated_at'],
 'pc_port_service_disruptions': ['port_service_disruption_id',
                                 'event_id',
                                 'port_asset_id',
                                 'terminal_asset_id',
                                 'transport_service_id',
                                 'disruption_type',
                                 'began_at',
                                 'estimated_restoration_at',
                                 'restored_at',
                                 'capacity_reduction_percent',
                                 'vessels_affected',
                                 'reported_delay_hours',
                                 'source_id',
                                 'research_claim_id',
                                 'verification_status',
                                 'metadata',
                                 'created_at',
                                 'updated_at'],
 'pc_rail_network_disruptions': ['rail_disruption_id',
                                 'event_id',
                                 'rail_network_id',
                                 'rail_link_id',
                                 'node_asset_id',
                                 'disruption_type',
                                 'start_at',
                                 'expected_restoration_at',
                                 'actual_restoration_at',
                                 'estimated_capacity_reduction_percent',
                                 'service_effect',
                                 'source_id',
                                 'research_claim_id',
                                 'verification_status',
                                 'metadata',
                                 'created_at',
                                 'updated_at'],
 'pc_rail_rolling_stock_units': ['rolling_stock_unit_id',
                                 'mobile_asset_id',
                                 'rail_network_id',
                                 'owner_entity_id',
                                 'operator_entity_id',
                                 'unit_identifier',
                                 'rolling_stock_type',
                                 'build_year',
                                 'gauge_mm',
                                 'axle_load_tonnes',
                                 'payload_tonnes',
                                 'traction_type',
                                 'operational_status',
                                 'valid_from',
                                 'valid_to',
                                 'source_id',
                                 'research_claim_id',
                                 'verification_status',
                                 'metadata',
                                 'created_at',
                                 'updated_at'],
 'pc_rail_service_runs': ['rail_service_run_id',
                          'transport_service_id',
                          'rail_network_id',
                          'operator_entity_id',
                          'origin_asset_id',
                          'destination_asset_id',
                          'scheduled_departure_at',
                          'actual_departure_at',
                          'scheduled_arrival_at',
                          'actual_arrival_at',
                          'service_status',
                          'container_teu',
                          'gross_tonnes',
                          'linked_event_id',
                          'source_id',
                          'research_claim_id',
                          'verification_status',
                          'metadata',
                          'created_at',
                          'updated_at'],
 'pc_research_claims': ['research_claim_id',
                        'research_project_id',
                        'research_question_id',
                        'claim_text',
                        'claim_type',
                        'verification_status',
                        'subject_type',
                        'subject_id',
                        'valid_from',
                        'valid_to',
                        'reported_at',
                        'confidence',
                        'supersedes_claim_id',
                        'metadata',
                        'created_at',
                        'updated_at'],
 'pc_research_hypotheses': ['research_hypothesis_id',
                            'research_project_id',
                            'hypothesis_text',
                            'hypothesis_status',
                            'alternative_to_id',
                            'assumptions',
                            'indicators',
                            'assessment',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_research_opportunities': ['research_opportunity_id',
                               'research_project_id',
                               'opportunity_type',
                               'title',
                               'sponsor_entity_id',
                               'candidate_entity_id',
                               'candidate_asset_id',
                               'corridor_key',
                               'evidence_level',
                               'research_status',
                               'rationale',
                               'constraints',
                               'metadata',
                               'created_at',
                               'updated_at'],
 'pc_research_projects': ['research_project_id',
                          'title',
                          'research_domain',
                          'question_summary',
                          'project_status',
                          'audience_codes',
                          'scope',
                          'owner_label',
                          'opened_at',
                          'closed_at',
                          'metadata',
                          'created_at',
                          'updated_at'],
 'pc_research_questions': ['research_question_id',
                           'research_project_id',
                           'parent_question_id',
                           'question_text',
                           'priority',
                           'question_status',
                           'answer_summary',
                           'due_at',
                           'metadata',
                           'created_at',
                           'updated_at'],
 'pc_road_border_observations': ['road_border_observation_id',
                                 'border_asset_id',
                                 'road_corridor_id',
                                 'observed_at',
                                 'crossing_direction',
                                 'wait_hours',
                                 'queue_vehicles',
                                 'restriction_type',
                                 'status',
                                 'related_event_id',
                                 'source_id',
                                 'research_claim_id',
                                 'verification_status',
                                 'metadata',
                                 'created_at',
                                 'updated_at'],
 'pc_road_disruptions': ['road_disruption_id',
                         'event_id',
                         'road_corridor_id',
                         'road_network_link_id',
                         'border_asset_id',
                         'disruption_type',
                         'start_at',
                         'expected_reopening_at',
                         'reopened_at',
                         'estimated_delay_hours',
                         'source_id',
                         'research_claim_id',
                         'verification_status',
                         'metadata',
                         'created_at',
                         'updated_at'],
 'pc_road_network_links': ['road_network_link_id',
                           'road_corridor_id',
                           'from_asset_id',
                           'to_asset_id',
                           'route_number',
                           'link_name',
                           'country',
                           'length_km',
                           'weight_limit_tonnes',
                           'height_limit_m',
                           'hazmat_allowed',
                           'status',
                           'valid_from',
                           'valid_to',
                           'source_id',
                           'research_claim_id',
                           'verification_status',
                           'metadata',
                           'created_at',
                           'updated_at'],
 'pc_screening_cases': ['screening_case_id',
                        'case_reference',
                        'subject_type',
                        'subject_id',
                        'submitted_name',
                        'screening_purpose',
                        'jurisdiction_codes',
                        'case_status',
                        'opened_at',
                        'closed_at',
                        'metadata'],
 'pc_screening_matches': ['screening_match_id',
                          'screening_case_id',
                          'sanctions_designation_id',
                          'match_status',
                          'match_score',
                          'match_basis',
                          'analyst_reason',
                          'reviewed_by_label',
                          'reviewed_at',
                          'metadata',
                          'created_at'],
 'pc_security_attribution_claims': ['attribution_claim_id',
                                    'event_id',
                                    'claimed_actor_entity_id',
                                    'claimed_actor_label',
                                    'attribution_kind',
                                    'reported_at',
                                    'claim_summary',
                                    'verification_state',
                                    'source_id',
                                    'research_claim_id',
                                    'verification_status',
                                    'metadata',
                                    'created_at',
                                    'updated_at'],
 'pc_security_operation_participants': ['security_operation_participant_id',
                                        'security_operation_id',
                                        'entity_id',
                                        'mobile_asset_id',
                                        'participant_role',
                                        'valid_from',
                                        'valid_to',
                                        'source_id',
                                        'research_claim_id',
                                        'verification_status',
                                        'metadata',
                                        'created_at',
                                        'updated_at'],
 'pc_security_operations': ['security_operation_id',
                            'operation_name',
                            'lead_entity_id',
                            'operating_area',
                            'operation_type',
                            'publicly_reported_start',
                            'publicly_reported_end',
                            'operation_status',
                            'source_id',
                            'research_claim_id',
                            'verification_status',
                            'metadata',
                            'created_at',
                            'updated_at'],
 'pc_shipbuilding_production_tasks': ['production_task_id',
                                      'shipbuilding_order_id',
                                      'shipbuilding_order_unit_id',
                                      'defence_programme_id',
                                      'shipyard_asset_id',
                                      'builder_entity_id',
                                      'task_type',
                                      'task_status',
                                      'planned_start',
                                      'actual_start',
                                      'planned_finish',
                                      'actual_finish',
                                      'workshare_percent',
                                      'source_id',
                                      'research_claim_id',
                                      'verification_status',
                                      'metadata',
                                      'created_at',
                                      'updated_at'],
 'pc_shipyard_capacity_history': ['shipyard_capacity_history_id',
                                  'shipyard_asset_id',
                                  'operator_entity_id',
                                  'observed_date',
                                  'metric_name',
                                  'metric_value',
                                  'metric_unit',
                                  'capacity_basis',
                                  'reported_backlog_quantity',
                                  'planned_or_actual',
                                  'source_id',
                                  'research_claim_id',
                                  'verification_status',
                                  'metadata',
                                  'created_at',
                                  'updated_at'],
 'pc_supply_chain_dependencies': ['supply_chain_dependency_id',
                                  'dependent_entity_id',
                                  'dependent_asset_id',
                                  'dependent_corridor_key',
                                  'provider_entity_id',
                                  'provider_asset_id',
                                  'provider_corridor_key',
                                  'dependency_type',
                                  'criticality',
                                  'substitute_available',
                                  'documented_basis',
                                  'valid_from',
                                  'valid_to',
                                  'source_id',
                                  'research_claim_id',
                                  'verification_status',
                                  'metadata',
                                  'created_at',
                                  'updated_at'],
 'pc_trucking_fleet_assignments': ['trucking_fleet_assignment_id',
                                   'entity_id',
                                   'mobile_asset_id',
                                   'depot_asset_id',
                                   'transport_service_id',
                                   'relationship_type',
                                   'assignment_from',
                                   'assignment_to',
                                   'operating_region',
                                   'source_id',
                                   'research_claim_id',
                                   'verification_status',
                                   'metadata',
                                   'created_at',
                                   'updated_at'],
 'pc_vessel_deployments': ['vessel_deployment_id',
                           'mobile_asset_id',
                           'operator_entity_id',
                           'transport_service_id',
                           'corridor_key',
                           'deployment_type',
                           'valid_from',
                           'valid_to',
                           'deployment_status',
                           'source_id',
                           'research_claim_id',
                           'verification_status',
                           'metadata',
                           'created_at',
                           'updated_at'],
 'pc_vessel_identity_history': ['vessel_identity_history_id',
                                'mobile_asset_id',
                                'identifier_type',
                                'identifier_value',
                                'valid_from',
                                'valid_to',
                                'jurisdiction',
                                'change_reason',
                                'source_id',
                                'research_claim_id',
                                'verification_status',
                                'metadata',
                                'created_at',
                                'updated_at'],
 'pc_weather_observations': ['weather_observation_id',
                             'provider',
                             'provider_record_id',
                             'weather_kind',
                             'hazard_type',
                             'issued_at',
                             'valid_from',
                             'valid_to',
                             'observed_at',
                             'latitude',
                             'longitude',
                             'geographic_scope',
                             'severity',
                             'metrics',
                             'corridor_key',
                             'event_id',
                             'source_id',
                             'source_record_uuid',
                             'source_url',
                             'metadata',
                             'created_at']}


# Older canonical tables provide an independent application-level connection test.
# Do not declare one "missing" merely because a metadata-registration query fails.
CORE_READ_TARGETS = {
    "pc_entities": "entity_id",
    "pc_assets": "asset_id",
    "pc_mobile_assets": "mobile_asset_id",
    "pc_events": "event_id",
    "pc_sources": "source_id",
    "pc_documents": "*",
    "pc_document_links": "*",
    "pc_sanctions_designations": "*",
    "pc_ingestion_jobs": "ingestion_job_id",
}

# Redact common accidental secrets before showing user-facing errors or exporting reports.
def safe_error(exc):
    msg = str(exc)
    msg = re.sub(r"(?i)(bearer\s+)[A-Za-z0-9._~+/-]+", r"\1[redacted]", msg)
    msg = re.sub(r"(?i)(apikey|api_key|service_role_key|access_token|authorization)[=:\s\"']+[A-Za-z0-9._~+/-]+", r"\1=[redacted]", msg)
    msg = re.sub(r"https?://[^\s\"']+", "[upstream URL redacted]", msg)
    return msg[:260]


def batch(items, size=12):
    items = list(items)
    for i in range(0, len(items), size):
        yield items[i:i+size]


def response_rows(query):
    return query.execute().data or []


def fetch_registry(sb, table_name, wanted_columns, target_names):
    """Read all matching metadata rows, paginating to avoid Supabase's 1000-row default."""
    rows=[]
    for names in batch(sorted(target_names), 12):
        offset=0
        while True:
            q=(sb.table(table_name)
                 .select(wanted_columns)
                 .in_("table_name", names)
                 .range(offset, offset+999))
            chunk=response_rows(q)
            rows.extend(chunk)
            if len(chunk)<1000:
                break
            offset+=1000
            if offset>=100000:
                raise RuntimeError("Registry pagination exceeded safety limit")
    return rows


def table_probe(sb, table, primary_key):
    """Check through the same REST endpoint that Streamlit apps normally use.

    SELECT with limit(1), not exact COUNT, to keep load low during an outage.
    An empty accessible table is PRESENT, not MISSING.
    """
    try:
        rows=response_rows(sb.table(table).select(primary_key).limit(1))
        return ("READABLE", "Sample record available" if rows else "Empty, readable table")
    except Exception as exc:
        s=safe_error(exc)
        lower=s.lower()
        if any(x in lower for x in ("timeout", "connection", "network", "temporarily", "failed to fetch", "name resolution")):
            return ("CONNECTIVITY_ERROR", s)
        # These can also mean stale PostgREST schema cache or lack of permissions;
        # never claim a physical table is missing from a REST error alone.
        if any(x in lower for x in ("404", "pgrst205", "pgrst204", "not found", "does not exist")):
            return ("NOT_EXPOSED_OR_MISSING", s)
        if any(x in lower for x in ("401", "403", "permission", "denied", "rls")):
            return ("ACCESS_ERROR", s)
        return ("QUERY_ERROR", s)


def compare_registry(table_names, entities, columns):
    """No database access needed: compare supplied registry snapshots to expected schema."""
    by_entity={}
    for r in entities:
        by_entity.setdefault(r.get("table_name"),[]).append(r)
    by_cols={}
    for r in columns:
        by_cols.setdefault(r.get("table_name"),set()).add(r.get("column_name"))
    result=[]
    for phase, tables in PHASE13_TABLES_BY_PHASE.items():
        for table in tables:
            expected=set(PHASE13_COLUMNS[table])
            actual=by_cols.get(table,set())
            reg=by_entity.get(table,[])
            active=[x for x in reg if x.get("active") is True]
            pk=PHASE13_PK[table]
            pk_match=(len(active)==1 and active[0].get("primary_key_column")==pk)
            missing=sorted(expected-actual)
            extra=sorted(actual-expected)
            if len(reg)==0:
                status="UNREGISTERED"
            elif len(reg)!=1 or not pk_match:
                status="REGISTRY_CONFLICT"
            elif missing:
                status="MISSING_COLUMNS"
            else:
                status="REGISTERED"
            result.append({
                "Phase":"13"+phase,
                "Table":table,
                "Registration":status,
                "Expected columns":len(expected),
                "Registered columns":len(actual),
                "Missing columns":len(missing),
                "Expected PK":pk,
                "Registered PK":reg[0].get("primary_key_column") if len(reg)==1 else "",
                "Missing names":", ".join(missing),
                "Extra columns":", ".join(extra),
            })
    return result


def run_audit(sb, check_physical=False):
    targets=set(PHASE13_PK)
    result={"version":APP_VERSION,
            "generated_at_utc":datetime.now(timezone.utc).isoformat(),
            "read_only":True,
            "registration":[], "connectivity":[], "errors":[],
            "notes":["Metadata checks use PostgREST, not raw SQL introspection.",
                     "A REST read failure cannot prove a physical table is missing.",
                     "Physical column types, FKs, indexes and RLS policies need SQL when management access recovers."]}
    try:
        entities=fetch_registry(sb,"pc_meta_entity_types",
                                "table_name,entity_type,primary_key_column,active,allow_insert",
                                targets)
        columns=fetch_registry(sb,"pc_meta_columns","table_name,column_name",targets)
        result["registration"]=compare_registry(targets,entities,columns)
    except Exception as exc:
        result["errors"].append("Registry query failed: "+safe_error(exc))

    for table, pk in CORE_READ_TARGETS.items():
        status,detail=table_probe(sb,table,pk)
        result["connectivity"].append({"Group":"Core / specialist", "Table":table,
                                       "Read status":status,"Detail":detail})

    if check_physical:
        for phase,tables in PHASE13_TABLES_BY_PHASE.items():
            for table in tables:
                status,detail=table_probe(sb,table,PHASE13_PK[table])
                result["connectivity"].append({"Group":"13"+phase,"Table":table,
                                               "Read status":status,"Detail":detail})
    return result


def audit_action_matrix(registry, connectivity):
    """Read-only triage. Never equate metadata absence with physical absence."""
    phases=[]
    for phase, tables in PHASE13_TABLES_BY_PHASE.items():
        rows=[r for r in registry if r.get("Phase")=="13"+phase]
        ready=sum(r.get("Registration")=="REGISTERED" for r in rows)
        unregistered=sum(r.get("Registration")=="UNREGISTERED" for r in rows)
        incomplete=sum(r.get("Registration") in ("REGISTRY_CONFLICT","MISSING_COLUMNS") for r in rows)
        probes=[r for r in connectivity if r.get("Group")=="13"+phase]
        failures=sum(r.get("Read status")!="READABLE" for r in probes)
        phases.append({"Phase":"13"+phase,"Expected":len(tables),"Registered":ready,
                       "Unregistered":unregistered,"Incomplete metadata":incomplete,
                       "REST probe failures":failures if probes else None,
                       "Probed":bool(probes)})
    return phases


def show_app():
    st.set_page_config(page_title="P&C · Database Diagnostics",page_icon="◈",layout="wide")
    # No local bypass: diagnostic access uses existing authorized Power Admin login.
    # If auth is not configured yet, this diagnostic fails closed rather than
    # exposing infrastructure/status details via the public Streamlit app.
    require_super_admin()
    st.title("Database Diagnostics")
    st.caption("Power & Corridors · read-only Streamlit diagnostics · "+APP_VERSION)
    st.info("This page uses your existing Supabase project connection, not the Supabase dashboard. "
            "It cannot run SQL migrations, change records or inspect RLS policies.")
    if os.getenv("PC_PHASE13_APPLY_ENABLED", "false").lower() == "true":
        st.warning("PC_PHASE13_APPLY_ENABLED is true in this deployment. "
                   "This diagnostic is still read-only, but review the separate Power Admin write controls.")
    sb=service_client()
    if sb is None:
        st.error("The service-role database connection is unavailable. "
                 "Check that the existing Power Admin Streamlit secrets are available. Do not paste keys here.")
        st.stop()

    st.subheader("Run checks")
    full=st.checkbox("Include individual read checks of all 58 Phase 13 tables",value=False,
                     help="More requests; useful when registry access works but one domain is failing.")
    if st.button("Run read-only diagnostics",type="primary"):
        with st.spinner("Checking the database through the same Supabase connection as Power Admin..."):
            result=run_audit(sb,check_physical=full)
        st.session_state["pc_db_diag_result"]=result

    result=st.session_state.get("pc_db_diag_result")
    if not result:
        st.caption("No database checks have been run in this session.")
        return

    for err in result["errors"]:
        st.error(err)
    reg=pd.DataFrame(result["registration"])
    connection=pd.DataFrame(result["connectivity"])
    if not reg.empty:
        total=len(reg)
        ready=int(reg["Registration"].eq("REGISTERED").sum())
        a,b,c=st.columns(3)
        a.metric("Registered / expected",f"{ready} / {total}")
        b.metric("13A–13B registered",f"{reg[(reg['Phase'].isin(['13A','13B'])) & reg['Registration'].eq('REGISTERED')].shape[0]} / 26")
        c.metric("13C–13F registered",f"{reg[(reg['Phase'].isin(['13C','13D','13E','13F'])) & reg['Registration'].eq('REGISTERED')].shape[0]} / 32")
        st.markdown("#### Registration by phase")
        phase_matrix=pd.DataFrame(audit_action_matrix(result["registration"],result["connectivity"]))
        st.dataframe(phase_matrix,use_container_width=True,hide_index=True)
        st.caption("Metadata registration, REST exposure and physical installation are separate checks. A missing registration or REST failure alone does not establish physical-table absence.")
        ab=phase_matrix[phase_matrix["Phase"].isin(["13A","13B"])]
        if not ab.empty and int(ab["Registered"].sum()) < 26:
            st.warning("13A–13B are not fully registered. Audit their migrations and existing physical objects in the Supabase SQL editor before applying guarded migrations. Do not infer absence from these registry counts.")
        if (phase_matrix["Incomplete metadata"]>0).any():
            st.error("Registry conflicts or missing column metadata detected. Review individual differences before enabling the Phase 13 canonical apply path.")
        if any(result["errors"]):
            st.error("Registry data could not be fully read; reported totals may be incomplete.")
        st.subheader("Phase 13 model registry")
        phase=st.selectbox("Show phase",["All","13A","13B","13C","13D","13E","13F"])
        visible=reg if phase=="All" else reg[reg["Phase"]==phase]
        st.dataframe(visible.drop(columns=["Missing names","Extra columns","Registered PK"],errors="ignore"),
                     use_container_width=True,hide_index=True)
        problem=visible[visible["Registration"]!="REGISTERED"]
        if not problem.empty:
            with st.expander("Registration differences",expanded=True):
                st.dataframe(problem,use_container_width=True,hide_index=True)
    st.subheader("Project REST read checks")
    if not connection.empty:
        st.dataframe(connection,use_container_width=True,hide_index=True)
        failed=connection[connection["Read status"]!="READABLE"]
        if not failed.empty:
            st.warning("A REST read failed. Review connectivity, API exposure and permissions before concluding a physical table is absent.")
    st.download_button("Export phase triage CSV",data=pd.DataFrame(audit_action_matrix(result["registration"],result["connectivity"])).to_csv(index=False),
                       file_name="pc_phase13_triage.csv",mime="text/csv")
    st.download_button("Export diagnostic JSON",data=json.dumps(result,indent=2,default=str),
                       file_name="pc_database_diagnostics.json",mime="application/json")
    if not reg.empty:
        st.download_button("Export registration CSV",data=reg.to_csv(index=False),
                           file_name="pc_phase13_registry.csv",mime="text/csv")
    st.caption("No query execution interface is exposed. This diagnostic never sends mutations or SQL RPC calls.")


if __name__ == "__main__":
    show_app()
